# Generated by Django 2.0.6 on 2018-07-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='wishlist',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
