# Generated by Django 2.0.6 on 2018-07-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180624_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='Unknown', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=3.5, max_digits=2),
        ),
        migrations.AddField(
            model_name='product',
            name='topseller',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
