# Generated by Django 2.0.6 on 2018-07-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180715_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='topseller',
        ),
        migrations.AddField(
            model_name='product',
            name='amountsold',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(default='Unknown', max_length=120),
        ),
    ]
