# Generated by Django 2.0.6 on 2018-07-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180715_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amountsold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
